export const CREATE_PRICE_DATA = "CREATE_PRICE_DATA";
export const CREATE_OTHER_DATA = "CREATE_OTHER_DATA";
export const DELETE_OTHER_DATA = "DELETE_OTHER_DATA";
export const SET_TICKER_NAME = "SET_TICKER_NAME";
